// Static content data — musicians, concerts, gallery, etc.

// en/no UI copy dictionary. Tag translatable elements with data-i18n="key"
// (or data-i18n-placeholder="key" for inputs) — renderI18n() in main.js
// walks these and sets textContent/placeholder from DICTIONARY[lang][key].
const DICTIONARY = {
  en: {
    navHome: 'Home',
    navAbout: 'About',
    navConcerts: 'Concerts',
    navMedia: 'Media',
    navContact: 'Contact',
    supportedBy: 'Supported by Arts Council Norway',
    heroKicker: 'SCANDINAVIAN CHAMBER SOLOISTS',
    heroTitle: 'Chamber music of international dimensions',
    heroQuote: '"A melting pot of talent from all over the world" — the ensemble\'s sound has been called a mini world of stringed instruments.',
    heroQuoteSource: 'EMIL OTTO SYVERTSEN, FÆDRELANDSVENNEN',
    heroCta1: 'About the ensemble',
    heroCta2: 'See concerts',
    aboutKicker: 'WHO WE ARE',
    aboutTitle: 'Musicians from five countries, one Kristiansand stage',
    aboutBody1: 'Scandinavian Chamber Soloists is a Kristiansand-based ensemble comprised of musicians from Norway, Sweden, the Netherlands, Armenia and Japan.',
    aboutBody2: 'Founded and led by violinist Loussine Azizian Idsøe, the ensemble has toured Norway and Denmark to critical acclaim since its 2019 debut.',
    aboutCta: 'Get in touch',
    musiciansKicker: 'THE MUSICIANS',
    concertsKicker: "WHAT'S NEXT",
    concertsTitle: 'Upcoming concerts',
    concertReadMore: 'Read more',
    mediaKicker: 'WATCH',
    mediaTitle: "Piazzolla's Spring, live in Trinitatis Church",
    mediaBody: 'Recorded live in Copenhagen, February 2020. The full performance features on our debut album.',
    mediaCta: 'Watch on YouTube',
    galleryKicker: 'GALLERY',
    galleryTitle: "From Grundtvig's Church, Copenhagen",
    contactTitle: 'Drop us a message',
    contactName: 'Your name',
    contactEmail: 'Email address',
    contactMessage: 'Message',
    contactSend: 'Send message',
    contactAddressLabel: 'ADDRESS',
    contactEmailLabel: 'EMAIL',
    contactPhoneLabel: 'PHONE',
    contactSuccess: 'Thanks — your message has been sent.',
    contactError: 'Something went wrong sending your message. Please try again or email us directly.',
  },
  no: {
    navHome: 'Hjem',
    navAbout: 'Om',
    navConcerts: 'Konserter',
    navMedia: 'Media',
    navContact: 'Kontakt',
    supportedBy: 'Støttet af Kulturrådet',
    heroKicker: 'SCANDINAVIAN CHAMBER SOLOISTS',
    heroTitle: 'Kammermusikk av internasjonal klasse',
    heroQuote: '«En smeltedigel av talent fra hele verden» — ensemblets klang er blitt kalt en mini-verden av strengeinstrumenter.',
    heroQuoteSource: 'EMIL OTTO SYVERTSEN, FÆDRELANDSVENNEN',
    heroCta1: 'Om ensemblet',
    heroCta2: 'Se konserter',
    aboutKicker: 'HVEM ER VI',
    aboutTitle: 'Musikere fra fem land, én scene i Kristiansand',
    aboutBody1: 'Scandinavian Chamber Soloists er et ensemble med musikere fra Norge, Sverige, Nederland, Armenia og Japan, med base i Kristiansand.',
    aboutBody2: 'Ensemblet er etablert og ledet av fiolinist Loussine Azizian Idsøe, og har turnert i Norge og Danmark med stor suksess siden debuten i 2019.',
    aboutCta: 'Ta kontakt',
    musiciansKicker: 'MUSIKERE',
    concertsKicker: 'KOMMENDE',
    concertsTitle: 'Kommende konserter',
    concertReadMore: 'Les mer',
    mediaKicker: 'SE VIDEO',
    mediaTitle: 'Piazzollas Vår, live i Trinitatis Kirke',
    mediaBody: 'Live-versjon spilt inn i København, februar 2020. Hele fremføringen finnes på vårt debutalbum.',
    mediaCta: 'Se på YouTube',
    galleryKicker: 'GALLERI',
    galleryTitle: 'Fra Grundtvigskirken, København',
    contactTitle: 'Send oss en melding',
    contactName: 'Navnet ditt',
    contactEmail: 'Email adresse',
    contactMessage: 'Beskjed',
    contactSend: 'Sende',
    contactAddressLabel: 'ADRESSE',
    contactEmailLabel: 'EMAIL',
    contactPhoneLabel: 'TELEFON',
    contactSuccess: 'Takk — meldingen din er sendt.',
    contactError: 'Noe gikk galt under sending. Prøv igjen eller send oss en e-post direkte.',
  },
};

// base layout: xPct/sizePct are % of the field's live width (responsive); y is px against the fixed-height field
const MUSICIANS = [
  { name: 'Loussine Azizian Idsøe', instrumentEn: 'VIOLIN', instrumentNo: 'FIOLIN', src: 'assets/musician-loussine.png', xPct: 42, y: 165, sizePct: 27 },
  { name: 'Yuka Sato', instrumentEn: 'VIOLIN', instrumentNo: 'FIOLIN', src: 'assets/musician-yuka.png', xPct: 71, y: 80, sizePct: 19 },
  { name: 'Piotr Slowik', instrumentEn: 'VIOLA', instrumentNo: 'BRATSJ', src: 'assets/musician-piotr.png', xPct: 19, y: 65, sizePct: 17 },
  { name: 'Anne Camilla Furre Thommesen', instrumentEn: 'VIOLA', instrumentNo: 'BRATSJ', src: 'assets/musician-annecamilla.png', xPct: 12, y: 230, sizePct: 21 },
  { name: 'Krisztina Tokaji Eikeset', instrumentEn: 'CELLO', instrumentNo: 'CELLO', src: 'assets/musician-krisztina.png', xPct: 62, y: 260, sizePct: 22 },
  { name: 'Jasper Havelaar', instrumentEn: 'CELLO', instrumentNo: 'CELLO', src: 'assets/musician-jasper.png', xPct: 87, y: 195, sizePct: 18 },
  { name: 'Jan Mathiasson', instrumentEn: 'DOUBLE BASS', instrumentNo: 'KONTRABASS', src: 'assets/musician-jan.png', xPct: 38, y: 310, sizePct: 20 },
  { name: 'Gunnhild Tønder', instrumentEn: 'PIANO/HARPSICHORD', instrumentNo: 'PIANO/CEMBALO', src: 'assets/musician-gunnhild.png', xPct: 89, y: 320, sizePct: 16 },
];

// structured per-concert data — each field (image, title, subtitle, date, time,
// location, description, programme) is kept flat/independent so it can later be
// swapped for a 1:1 API response shape.
const CONCERTS_EN = [
  {
    id: 'concert-1',
    image: 'assets/concert-1.jpg',
    title: 'The Seven Sayings',
    subtitle: 'J. Haydn — The Seven Last Words of Christ',
    date: '18 April 2026',
    time: '6:00 pm',
    location: 'Kristiansand Cathedral, Norway',
    description: 'A meditation for Good Friday: Haydn\'s string-quartet reflections on Christ\'s final words, performed in the resonant nave of Kristiansand Cathedral.',
    programme: [
      { composer: 'J. Haydn', piece: 'The Seven Last Words of Christ' },
      { composer: 'G. Fauré', piece: 'Après un rêve' },
      { composer: 'S. Barber', piece: 'Adagio for Strings' },
    ],
  },
  {
    id: 'concert-2',
    image: 'assets/concert-2.jpg',
    title: 'Stabat Mater',
    subtitle: 'G. Pergolesi — Stabat Mater',
    date: '18 April 2026',
    time: '8:00 pm',
    location: 'Lillesand Kirke',
    description: 'Pergolesi\'s final masterwork paired with a selection of baroque laments, featuring soprano and alto soloists alongside the ensemble.',
    programme: [
      { composer: 'G. Pergolesi', piece: 'Stabat Mater' },
      { composer: 'A. Vivaldi', piece: 'Nulla in mundo pax sincera' },
      { composer: 'T. Albinoni', piece: 'Adagio in G minor' },
      { composer: 'H. Purcell', piece: "Dido's Lament" },
      { composer: 'J.S. Bach', piece: 'Erbarme dich' },
    ],
  },
  {
    id: 'concert-3',
    image: 'assets/concert-3.png',
    title: 'Tall Ships Races',
    subtitle: 'Vivaldi & Grieg — Midnight Concert',
    date: '31 July 2026',
    time: 'Midnight',
    location: 'Odderøya, Kristiansand',
    description: 'A midnight concert on the harbour in connection with the Tall Ships Races, pairing Italian baroque with Norwegian romanticism under open sky.',
    programme: [
      { composer: 'A. Vivaldi', piece: 'The Four Seasons: Summer' },
      { composer: 'E. Grieg', piece: 'Holberg Suite' },
      { composer: 'J. Sibelius', piece: 'Valse Triste' },
      { composer: 'O. Respighi', piece: 'Ancient Airs and Dances' },
    ],
  },
];

const CONCERTS_NO = [
  {
    id: 'concert-1',
    image: 'assets/concert-1.jpg',
    title: 'De syv ord',
    subtitle: 'J. Haydn — Jesu syv siste ord på korset',
    date: '18. april 2026',
    time: '18:00',
    location: 'Kristiansand Domkirke',
    description: 'En langfredagsmeditasjon: Haydns strykekvartettrefleksjoner over Kristi siste ord, fremført i Kristiansand Domkirkes klangfulle kirkerom.',
    programme: [
      { composer: 'J. Haydn', piece: 'Jesu syv siste ord på korset' },
      { composer: 'G. Fauré', piece: 'Après un rêve' },
      { composer: 'S. Barber', piece: 'Adagio for strykere' },
    ],
  },
  {
    id: 'concert-2',
    image: 'assets/concert-2.jpg',
    title: 'Stabat Mater',
    subtitle: 'G. Pergolesi — Stabat Mater',
    date: '18. april 2026',
    time: '20:00',
    location: 'Lillesand Kirke',
    description: 'Pergolesis siste mesterverk sammen med et utvalg barokke klagesanger, med sopran- og altsolister sammen med ensemblet.',
    programme: [
      { composer: 'G. Pergolesi', piece: 'Stabat Mater' },
      { composer: 'A. Vivaldi', piece: 'Nulla in mundo pax sincera' },
      { composer: 'T. Albinoni', piece: 'Adagio i g-moll' },
      { composer: 'H. Purcell', piece: 'Didos klagesang' },
      { composer: 'J.S. Bach', piece: 'Erbarme dich' },
    ],
  },
  {
    id: 'concert-3',
    image: 'assets/concert-3.png',
    title: 'Tall Ships Races',
    subtitle: 'Vivaldi og Grieg — Midnattskonsert',
    date: '31. juli 2026',
    time: 'Midnatt',
    location: 'Odderøya, Kristiansand',
    description: 'En midnattskonsert på havnen i forbindelse med Tall Ships Races, som forener italiensk barokk med norsk romantikk under åpen himmel.',
    programme: [
      { composer: 'A. Vivaldi', piece: 'De fire årstider: Sommer' },
      { composer: 'E. Grieg', piece: 'Holbergsuiten' },
      { composer: 'J. Sibelius', piece: 'Valse Triste' },
      { composer: 'O. Respighi', piece: 'Antikke danser og arier' },
    ],
  },
];

const CONCERTS = { en: CONCERTS_EN, no: CONCERTS_NO };

const GALLERY_IMAGES = [
  'assets/gallery-1.jpg',
  'assets/gallery-2.jpg',
  'assets/gallery-3.png',
  'assets/gallery-4.jpeg',
  'assets/gallery-5.jpg',
  'assets/gallery-6.jpg',
  'assets/gallery-7.jpg',
  'assets/gallery-8.jpg',
];
